# Generated by Django 4.2.3 on 2023-07-11 00:31

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(default='MX', max_length=2),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=3000000),
        ),
    ]
