# Generated by Django 4.2.3 on 2023-12-13 13:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='city/photos'),
        ),
    ]
