# Generated by Django 4.2.3 on 2023-07-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_city_country_city_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default='photos/galicia.jpg', upload_to='city/photos'),
        ),
    ]
